#!/usr/bin/env bash

set -eux -o pipefail

# pull the image before so we dont first remove the container and then pull
docker pull clouddrove/pritunl:{{ pritunl_version }}

docker rm -f -v pritunl || :

docker run --name pritunl --privileged \
    -v "{{ pritunl_path }}":/var/lib/pritunl \
    -v "{{ mongo_path }}":/var/lib/mongodb \
    -v "{{ pritunl_path }}/pritunl.conf":/etc/pritunl.conf \
    -v "{{ pritunl_log }}":{{ pritunl_log }} \
	-v pritunl-conf:/etc \
	-p 1194:1194/udp \
	-p 1194:1194/tcp \
	-p 80:80/tcp \
	-p 443:443/tcp \
	clouddrove/pritunl:{{ pritunl_version }}
