#!/usr/bin/env bash

set -eux -o pipefail

# pull the image before so we dont first remove the container and then pull
docker pull clouddrove/pritunl:{{ pritunl_version }}

docker rm -f -v pritunl || :

docker run -u root --net=host --rm --name pritunl \
   -p '80:80' \
   -p '443:443' \
   -p '1194:1194/udp' \
   -p '1194:1194/tcp' \
   -v "{{ pritunl_path }}":/var/lib/pritunl \
   -v "{{ pritunl_mongo_path }}":/var/lib/mongodb \
     clouddrove/pritunl:{{ pritunl_version }}
